name: model_train

permissions:
  id-token: write
  contents: write

on:
  - push  # Trigger the workflow on push events

jobs:
  run:
    runs-on: ubuntu-latest  # Run the workflow on Ubuntu latest

    steps:
      - uses: iterative/setup-cml@v2  # Set up CML environment (assuming this action exists)
      - uses: actions/checkout@v3  # Checkout the code from the repository
      - name: Train mode
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Access secrets securely
      
        run: |  # Multi-line command using heredoc syntax
          pip install -r requirements.txt
          python train_model.py

      - name: Generate model score report
        run: |  # Multi-line command for generating report
          echo # RF and LR Model Score" > report.md
          cat scores.txt >> report.md  # Append report data

      - name: Generate model analysis report (corrected)
        run: |  # Multi-line command for generating analysis report
          echo "# Confusion Matrix and Feature Importance" > report1.md
          echo '|[Image of ConfusionMatrix.png](ConfusionMatrix.png "ConfusionMatrix")' >> report1.md  # Corrected image reference
          echo '|[Image of FeatureImportance.png](FeatureImportance.png "FeatureImportance")' >> report1.md  # Corrected image reference


      - name: Combine reports (corrected)
        run: |  # Multi-line command for combining reports
          cat report.md report1.md > combined_file.md  # Corrected file name
          cml comment create combined_file.md

